---
title: "Teaching Biostats"
---

This site contains some of my materials for teaching introductory statistics and computation to biologists (undergraduate) as well as documentation for how to make such teaching material. The material is freely available. 

***

# R package `exams`

This is a a quick guide to the package `exams` which makes randomised MCQs that you can export to online learning management systems (we use blackboard). Here, random number generators are your friend. Just watch out for rounding errors. You can make the output nicer with `knitr::kable()` or similar HTML formatting.

***

# Lectures on statistical modelling

These are my lecture handouts with the option to download the .rmd file. The students get three lectures on statistical models from me, which is not a lot for an introductory class. The lectures thus focus on understanding the concepts of slopes and intercepts of linear models and introduces fixed and random slope models, as well as interactions. It takes a GLM centric approach with less emphasis on classifying linear models according to data types.  

I used code folding for creating question and hidden answers.

***

# Biostats tutorials with `learnr`

The [biostats.tutorials](https://github.com/jacintak/biostats/tree/master/biostats.tutorials) folder on my biostats repo contains an R package of learnr tutorials for biostats. You will need to install it from the subdirectory so you don't get all my website files too. See the README.

***
